repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Do not display the score
            "--rcfile=.pylintrc", # Use the .pylintrc file
            "--load-plugins=pylint.extensions.docparams", # Load the docparams plugin
          ]
